---
- name: Setup Raspberry Pi
  hosts: raspberry_pi
  become: yes # Isso permite executar comandos com privilégios de superusuário

  tasks:
    - name: Install cowsay
      package:
        name: cowsay
        state: present
