---
- name: Setup Raspberry Pi
  hosts: raspberry_pi
  become: yes # Isso permite executar comandos com privilégios de superusuário

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Vim
      apt:
        name: vim
        state: present
