---
- name: Hello World Playbook
  hosts: rpis
  become: true
  vars_files: "vars.yml"

  tasks:
    - name: Print hello world
      debug:
        msg: "Hello, World! I'm {{ inventory_hostname }} with IP {{ ansible_host }}"

    - name: Install cowsay
      package:
        name: cowsay
        state: present
